service: serverless-graphql
provider:
  name: aws
  runtime: nodejs12.x
  region: me-south-1

functions:
  graphql:
    handler: src\index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src\index.handler
    events:
      - http:
          path: playground
          method: get
plugins:
  - serverless-offline
  - serverless-webpack
custom:
   webpack:
    includeModuled: true
